version: '3.5'
services:
  go-course-web:
    platform: linux/amd64
    container_name: go-course-web
    build:
      context: ./.docker/mySQL
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-course-web
    ports:
      - "3320:3306"
    volumes:
      - ./.docker/mySQL/init.sql:/docker-entrypoint-initdb.d/init.sql